# Walkthrough: Loading and Visualizing Extracted Objects
This Jupyter Notebook provides a step-by-step guide on how to load and visualize extracted objects. Follow the instructions below to understand the workflow.

## The construction pipeline
This repo hosts a pipeline for constructing semantic scenegraph based on RGBD images captured from Iphone. The pipeline can be executed by the following command
```bash
python build_map.py <path to RGBD images dataset>
```
The pipeline is as follow
1. Images, odometry, and camera intrinsics are loaded from the dataset
2. Segmentation, VLM, Captioning, and LLM models are loaded
3. Each images are segmented with Segmentation model
4. Fragments are cropped out and projected onto a 3d space
5. Crops are semantically embedded with Image Embedding model
6. Crops and Fragments are associated and merged with each other based on their semantic and geometric similarity
7. After all images are processed, the captioning and embedding models go through all objects and label them
8. Extract labels and edges based on image and semantic dat

## The object class (Model.tracker.MapObject)
The `MapObject` class is used to store information about objects. It includes the following attributes:
- `pcd`: `o3d.geometry.PointCloud` - The point cloud representation of the object.
- `bbox`: `o3d.geometry.AxisAlignedBoundingBox` - The bounding box of the object.
- `clip_ft`: `torch.Tensor` - The aggregated feature tensor (from image).
- `text_ft`: `torch.Tensor` - The aggregated feature tensor (from semantic label).
- `crops`: `List[tuple]` - A list of tuples containing crop information (from images) (`crop`, `xyxy`, `frame_idx`, `score`).
- `oid`: `Optional[int]` - The object ID (optional).
- `class_ids`: `List[int]` - A list of class IDs associated with the object.
- `class_name`: `str` - The name of the object's class.
- `detections`: `List[Detection]` - A list of detections associated with the object.
- `num_views`: `int` - The number of views in which the object is visible (default is 1).
- `total_weight`: `float` - The total weight of the object (default is 1.0).

## The tracker class (Model.tracker.ObjectTracker3D)
The `ObjectTracker3D` class is responsible for managing and associating objects in the dataset. It includes the following attributes:
- `objects`: `MapObjectList` - A list to store all the objects.
- `voxel_size`: `float` - The voxel size used for downsampling point clouds.
- `w_geo`: `float` - The weight for geometric similarity during object association.
- `w_sem`: `float` - The weight for semantic similarity during object association.
- `edges`: `List[tuple]` - A list of edges representing relationships between objects.
- `match_threshold`: `float` - The threshold for matching objects based on similarity.
- `max_points`: `int` - The maximum number of points allowed in the point cloud representation of an object.

In [1]:
from Model.tracker import *
from utils.logger import *
import open3d as o3d
from utils.io import *
from Model.models import *
from utils.data_construction.plot_graph import *
from utils.graph import *
import json
from VPR_im2im.utils.data_loader import *
%load_ext autoreload
%autoreload 2

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.

In [3]:
with open("graph_dataset/graph.json", 'rb') as f:
    g = json.load(f)

In [12]:
g['edges'][50]

{'src_id': 10,
 'dst_id': 22,
 'src_name': 'red office stool',
 'dst_name': 'red office chair',
 'relation': 'near'}

In [13]:
df = pd.read_csv('graph_dataset/raw_scans/iphone/3578aa5730/odometry.csv')

In [14]:
df.head()

     timestamp   frame    x    y    z        qx        qy        qz        qw
0  6321.641064       0  0.0  0.0  0.0  0.600268 -0.664773  0.322900  0.305762
1  6321.657732       1  0.0  0.0  0.0  0.600902 -0.665074  0.322655  0.304116
2  6321.674400       2  0.0  0.0  0.0  0.600666 -0.665195  0.322539  0.304441
3  6321.691068       3  0.0  0.0  0.0  0.600144 -0.665090  0.322510  0.305727
4  6321.707735       4  0.0  0.0  0.0  0.598922 -0.665001  0.322512  0.308305

In [2]:
# Initialize the logger for tracking and debugging
logger = build_logger()

# Load the full tracker from the specified checkpoint directory using the logger
tracker, _ = load_full_tracker("graph_dataset/raw_extration/checkpoints", logger)

[21:30:15] [INFO] [Resume] Loading tracker checkpoint from: graph_dataset/raw_extration/checkpoints

[21:30:15] [INFO] [Resume] Loaded object_0000
[21:30:15] [INFO] [Resume] Loaded object_0001
[21:30:15] [INFO] [Resume] Loaded object_0002
[21:30:15] [INFO] [Resume] Loaded object_0003
[21:30:15] [INFO] [Resume] Loaded object_0004
[21:30:15] [INFO] [Resume] Loaded object_0005
[21:30:15] [INFO] [Resume] Loaded object_0006
[21:30:15] [INFO] [Resume] Loaded object_0007
[21:30:15] [INFO] [Resume] Loaded object_0008
[21:30:15] [INFO] [Resume] Loaded object_0009
[21:30:15] [INFO] [Resume] Loaded object_0010
[21:30:15] [INFO] [Resume] Loaded object_0011
[21:30:15] [INFO] [Resume] Loaded object_0012
[21:30:15] [INFO] [Resume] Loaded object_0013
[21:30:15] [INFO] [Resume] Loaded object_0014
[21:30:15] [INFO] [Resume] Loaded object_0015
[21:30:15] [INFO] [Resume] Loaded object_0016
[21:30:15] [INFO] [Resume] Loaded object_0017
[21:30:15] [INFO] [Resume] Loaded object_0018
[21:30:15] [INFO] [Resume] Loaded object_0019
[21:30:15] [INFO] [Resume] Loaded object_0020
[21:30:15] [INFO] [Resume] Loaded object_0021
[21:30:15] [INFO] [Resume] Loaded object_0022
[21:30:15] [INFO] [Resume] Loaded object_0023
[21:30:15] [INFO] [Resume] Loaded object_0024
[21:30:15] [INFO] [Resume] Loaded object_0025
[21:30:15] [INFO] [Resume] Loaded object_0026
[21:30:15] [INFO] [Resume] Loaded object_0027
[21:30:15] [INFO] [Resume] Loaded object_0028
[21:30:15] [INFO] [Resume] Loaded object_0029
[21:30:15] [INFO] [Resume] Loaded object_0030
[21:30:15] [INFO] [Resume] Loaded object_0031
[21:30:15] [INFO] [Resume] Loaded object_0032
[21:30:15] [INFO] [Resume] Loaded object_0033
[21:30:15] [INFO] [Resume] Loaded object_0034
[21:30:15] [INFO] [Resume] Loaded object_0035
[21:30:15] [INFO] [Resume] Loaded object_0036
[21:30:15] [INFO] [Resume] Loaded object_0037
[21:30:15] [INFO] [Resume] Loaded object_0038
[21:30:15] [INFO] [Resume] Loaded object_0039
[21:30:15] [INFO] [Resume] Loaded object_0040
[21:30:15] [INFO] [Resume] Loaded object_0041
[21:30:15] [INFO] [Resume] Loaded object_0042
[21:30:15] [INFO] [Resume] Loaded object_0043
[21:30:15] [INFO] [Resume] Loaded object_0044
[21:30:15] [INFO] [Resume] Loaded object_0045
[21:30:15] [INFO] [Resume] Loaded object_0046
[21:30:15] [INFO] [Resume] Loaded object_0047
[21:30:15] [INFO] [Resume] Loaded object_0048
[21:30:15] [INFO] [Resume] Loaded object_0049
[21:30:15] [INFO] [Resume] Loaded object_0050
[21:30:15] [INFO] [Resume] Loaded object_0051
[21:30:15] [INFO] [Resume] Loaded object_0052
[21:30:15] [INFO] [Resume] Loaded object_0053
[21:30:15] [INFO] [Resume] Loaded object_0054
[21:30:15] [INFO] [Resume] Loaded object_0055
[21:30:15] [INFO] [Resume] Loaded object_0056
[21:30:15] [INFO] [Resume] Loaded object_0057
[21:30:15] [INFO] [Resume] Loaded object_0058
[21:30:15] [INFO] [Resume] Loaded object_0059
[21:30:15] [INFO] [Resume] Loaded object_0060
[21:30:15] [INFO] [Resume] Loaded object_0061
[21:30:15] [INFO] [Resume] Loaded object_0062
[21:30:15] [INFO] [Resume] Loaded object_0063
[21:30:15] [INFO] [Resume] Loaded object_0064
[21:30:15] [INFO] [Resume] Loaded object_0065
[21:30:15] [INFO] [Resume] Loaded object_0066
[21:30:15] [INFO] [Resume] Loaded object_0067
[21:30:15] [INFO] [Resume] Loaded object_0068
[21:30:15] [INFO] [Resume] Loaded object_0069
[21:30:15] [INFO] [Resume] Loaded object_0070
[21:30:15] [INFO] [Resume] Loaded object_0071
[21:30:15] [INFO] [Resume] Loaded object_0072
[21:30:15] [INFO] [Resume] Loaded object_0073
[21:30:15] [INFO] [Resume] Loaded object_0074
[21:30:15] [INFO] [Resume] Loaded object_0075
[21:30:15] [INFO] [Resume] Loaded object_0076
[21:30:15] [INFO] [Resume] Loaded object_0077
[21:30:15] [INFO] [Resume] Loaded object_0078
[21:30:15] [INFO] [Resume] Loaded object_0079
[21:30:15] [INFO] [Resume] Loaded object_0080
[21:30:15] [INFO] [Resume] Loaded object_0081
[21:30:15] [INFO] [Resume] Loaded object_0082
[21:30:15] [INFO] [Resume] Loaded object_0083
[21:30:15] [INFO] [Resume] Loaded object_0084
[21:30:15] [INFO] [Resume] Loaded object_0085
[21:30:15] [INFO] [Resume] Loaded object_0086
[21:30:15] [INFO] [Resume] Loaded object_0087
[21:30:15] [INFO] [Resume] Loaded object_0088
[21:30:15] [INFO] [Resume] Loaded object_0089
[21:30:15] [INFO] [Resume] Loaded object_0090
[21:30:15] [INFO] [Resume] Loaded object_0091
[21:30:15] [INFO] [Resume] Loaded object_0092
[21:30:15] [INFO] [Resume] Loaded object_0093
[21:30:15] [INFO] [Resume] Loaded object_0094
[21:30:15] [INFO] [Resume] Loaded object_0095
[21:30:15] [INFO] [Resume] Loaded object_0096
[21:30:15] [INFO] [Resume] Loaded object_0097
[21:30:15] [INFO] [Resume] Loaded object_0098
[21:30:15] [INFO] [Resume] Loaded object_0099
[21:30:15] [INFO] [Resume] Loaded object_0100
[21:30:15] [INFO] [Resume] Loaded object_0101
[21:30:15] [INFO] [Resume] Loaded object_0102
[21:30:15] [INFO] [Resume] Loaded object_0103
[21:30:15] [INFO] [Resume] Loaded object_0104
[21:30:15] [INFO] [Resume] Loaded object_0105
[21:30:15] [INFO] [Resume] Loaded object_0106
[21:30:15] [INFO] [Resume] Loaded object_0107
[21:30:15] [INFO] [Resume] Loaded object_0108
[21:30:15] [INFO] [Resume] Loaded object_0109
[21:30:15] [INFO] [Resume] Loaded object_0110
[21:30:15] [INFO] [Resume] Loaded object_0111
[21:30:15] [INFO] [Resume] Loaded object_0112
[21:30:15] [INFO] [Resume] Loaded object_0113
[21:30:15] [INFO] [Resume] Loaded object_0114
[21:30:15] [INFO] [Resume] Loaded object_0115
[21:30:15] [INFO] [Resume] Loaded object_0116
[21:30:15] [INFO] [Resume] Loaded object_0117
[21:30:15] [INFO] [Resume] Loaded object_0118
[21:30:15] [INFO] [Resume] Loaded object_0119
[21:30:15] [INFO] [Resume] Loaded object_0120
[21:30:15] [INFO] [Resume] Loaded object_0121
[21:30:15] [INFO] [Resume] Loaded object_0122
[21:30:15] [INFO] [Resume] Loaded object_0123
[21:30:15] [INFO] [Resume] Loaded object_0124
[21:30:15] [INFO] [Resume] Loaded object_0125
[21:30:15] [INFO] [Resume] Loaded object_0126
[21:30:15] [INFO] [Resume] Loaded object_0127
[21:30:15] [INFO] [Resume] Loaded object_0128
[21:30:15] [INFO] [Resume] Loaded object_0129
[21:30:15] [INFO] [Resume] Loaded object_0130
[21:30:15] [INFO] [Resume] Loaded object_0131
[21:30:15] [INFO] [Resume] Loaded object_0132
[21:30:15] [INFO] [Resume] Loaded object_0133
[21:30:15] [INFO] [Resume] Loaded object_0134
[21:30:15] [INFO] [Resume] Loaded object_0135
[21:30:15] [INFO] [Resume] Loaded object_0136
[21:30:15] [INFO] [Resume] Loaded object_0137
[21:30:15] [INFO] [Resume] Loaded object_0138
[21:30:15] [INFO] [Resume] Loaded object_0139
[21:30:15] [INFO] [Resume] Loaded object_0140
[21:30:15] [INFO] [Resume] Loaded object_0141
[21:30:15] [INFO] [Resume] Loaded object_0142
[21:30:15] [INFO] [Resume] Loaded object_0143
[21:30:15] [INFO] [Resume] Loaded object_0144
[21:30:15] [INFO] [Resume] Loaded object_0145
[21:30:15] [INFO] [Resume] Loaded object_0146
[21:30:15] [INFO] [Resume] Loaded object_0147
[21:30:15] [INFO] [Resume] Loaded object_0148
[21:30:15] [INFO] [Resume] Loaded object_0149
[21:30:15] [INFO] [Resume] Loaded object_0150
[21:30:15] [INFO] [Resume] Loaded object_0151
[21:30:15] [INFO] [Resume] Loaded object_0152
[21:30:15] [INFO] [Resume] Loaded object_0153
[21:30:15] [INFO] [Resume] Loaded object_0154
[21:30:15] [INFO] [Resume] Loaded object_0155
[21:30:15] [INFO] [Resume] Loaded object_0156
[21:30:15] [INFO] [Resume] Loaded object_0157
[21:30:15] [INFO] [Resume] Loaded object_0158
[21:30:15] [INFO] [Resume] Loaded object_0159
[21:30:15] [INFO] [Resume] Loaded object_0160
[21:30:15] [INFO] [Resume] Loaded object_0161
[21:30:15] [INFO] [Resume] Loaded object_0162
[21:30:15] [INFO] [Resume] Loaded object_0163
[21:30:15] [INFO] [Resume] Loaded object_0164
[21:30:15] [INFO] [Resume] Loaded object_0165
[21:30:15] [INFO] [Resume] Loaded object_0166
[21:30:15] [INFO] [Resume] Loaded object_0167
[21:30:15] [INFO] [Resume] Loaded object_0168
[21:30:15] [INFO] [Resume] Loaded object_0169
[21:30:15] [INFO] [Resume] Loaded object_0170
[21:30:15] [INFO] [Resume] Loaded object_0171
[21:30:15] [INFO] [Resume] Loaded object_0172
[21:30:15] [INFO] [Resume] Loaded object_0173
[21:30:15] [INFO] [Resume] Loaded object_0174
[21:30:15] [INFO] [Resume] Loaded object_0175
[21:30:15] [INFO] [Resume] Loaded object_0176
[21:30:15] [INFO] [Resume] Loaded object_0177
[21:30:15] [INFO] [Resume] Loaded object_0178
[21:30:15] [INFO] [Resume] Loaded object_0179
[21:30:15] [INFO] [Resume] Loaded object_0180
[21:30:15] [INFO] [Resume] Loaded object_0181
[21:30:15] [INFO] [Resume] Loaded object_0182
[21:30:15] [INFO] [Resume] Loaded object_0183
[21:30:15] [INFO] [Resume] Loaded object_0184
[21:30:15] [INFO] [Resume] Loaded object_0185
[21:30:15] [INFO] [Resume] Loaded object_0186
[21:30:15] [INFO] [Resume] Loaded object_0187
[21:30:15] [INFO] [Resume] Loaded object_0188
[21:30:15] [INFO] [Resume] Loaded object_0189
[21:30:15] [INFO] [Resume] Loaded object_0190
[21:30:15] [INFO] [Resume] Loaded object_0191
[21:30:15] [INFO] [Resume] Loaded object_0192
[21:30:15] [INFO] [Resume] Loaded object_0193
[21:30:15] [INFO] [Resume] Loaded object_0194
[21:30:15] [INFO] [Resume] Loaded object_0195
[21:30:15] [INFO] [Resume] Loaded object_0196
[21:30:15] [INFO] [Resume] Loaded object_0197
[21:30:15] [INFO] [Resume] Loaded object_0198
[21:30:15] [INFO] [Resume] Loaded object_0199
[21:30:15] [INFO] [Resume] Loaded object_0200
[21:30:15] [INFO] [Resume] Loaded object_0201
[21:30:15] [INFO] [Resume] Loaded object_0202
[21:30:15] [INFO] [Resume] Loaded object_0203
[21:30:15] [INFO] [Resume] Loaded object_0204
[21:30:15] [INFO] [Resume] Loaded object_0205
[21:30:15] [INFO] [Resume] Loaded object_0206
[21:30:15] [INFO] [Resume] Loaded object_0207
[21:30:15] [INFO] [Resume] Loaded object_0208
[21:30:15] [INFO] [Resume] Loaded object_0209
[21:30:15] [INFO] [Resume] Loaded object_0210
[21:30:15] [INFO] [Resume] Loaded object_0211
[21:30:15] [INFO] [Resume] Loaded object_0212
[21:30:15] [INFO] [Resume] Loaded object_0213
[21:30:15] [INFO] [Resume] Loaded object_0214
[21:30:15] [INFO] [Resume] Loaded object_0215
[21:30:15] [INFO] [Resume] Loaded object_0216
[21:30:15] [INFO] [Resume] Loaded object_0217
[21:30:15] [INFO] [Resume] Loaded object_0218
[21:30:15] [INFO] [Resume] Loaded object_0219
[21:30:15] [INFO] [Resume] Loaded object_0220
[21:30:15] [INFO] [Resume] Loaded object_0221
[21:30:15] [INFO] [Resume] Loaded object_0222
[21:30:15] [INFO] [Resume] Loaded object_0223
[21:30:15] [INFO] [Resume] Loaded object_0224
[21:30:15] [INFO] [Resume] Loaded object_0225
[21:30:15] [INFO] [Resume] Loaded object_0226
[21:30:15] [INFO] [Resume] Loaded object_0227
[21:30:15] [INFO] [Resume] Loaded object_0228
[21:30:15] [INFO] [Resume] Loaded object_0229
[21:30:15] [INFO] [Resume] Loaded object_0230
[21:30:15] [INFO] [Resume] Loaded object_0231
[21:30:15] [INFO] [Resume] Loaded 232 objects.
[21:30:15] [INFO] [Resume] Loaded 696 edges.
[21:30:15] [INFO] [Resume] Resume will start after frame 15810

## Room assignment
As of the moment, room assignment is done manually by human. The program will display an overlay of detected objects onto a floorplan generated by the SLAM process. Human will manually draw polygon and define room names.

In [3]:
# The method below will generate an html file
# After the file is generated, user will open it on browser and define rooms through it
plot_scene_graph_over_floorplan_manual(tracker, "graph_dataset/floorplan.png", outfile="graph_dataset/scene_graph.html")

[(0, 21, {'rtype': 'near', 'score': 0.21096969617076589, 'dist': 0.9336244810789158, 'src': 'white desktop printer', 'dst': 'research poster board'}), (0, 7, {'rtype': 'near', 'score': 0.06768075045367923, 'dist': 1.6157721122187716, 'src': 'white desktop printer', 'dst': 'wooden door handle'}), (0, 20, {'rtype': 'near', 'score': 0.11053802418474282, 'dist': 1.3214374461924714, 'src': 'white desktop printer', 'dst': 'wall posters display'}), (0, 1, {'rtype': 'near', 'score': 0.1287320429726476, 'dist': 1.2300133532337398, 'src': 'white desktop printer', 'dst': 'red office chair'}), (0, 19, {'rtype': 'near', 'score': 0.1398265047816346, 'dist': 1.1804117455373975, 'src': 'white desktop printer', 'dst': 'Poster on wall.'}), (1, 34, {'rtype': 'near', 'score': 0.12258124813295253, 'dist': 1.259388752261145, 'src': 'red office chair', 'dst': 'Large white board'}), (1, 37, {'rtype': 'near', 'score': 0.03803013227676244, 'dist': 1.9616259199896944, 'src': 'red office chair', 'dst': 'Black electronic rack.'}), (1, 36, {'rtype': 'near', 'score': 0.10474272876993038, 'dist': 1.3537489051665368, 'src': 'red office chair', 'dst': 'Large white board'}), (1, 0, {'rtype': 'near', 'score': 0.1287320429726476, 'dist': 1.2300133532337398, 'src': 'red office chair', 'dst': 'white desktop printer'}), (3, 6, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.9182910540887181, 'src': 'wooden office shelf', 'dst': 'wooden display board'}), (3, 5, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.7986884834814179, 'src': 'wooden office shelf', 'dst': 'beige air purifier'}), (3, 4, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.7631805517051384, 'src': 'wooden office shelf', 'dst': 'white office printer'}), (4, 3, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.7631805517051384, 'src': 'white office printer', 'dst': 'wooden office shelf'}), (4, 6, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.5237625284579484, 'src': 'white office printer', 'dst': 'wooden display board'}), (4, 5, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.07075216908286101, 'src': 'white office printer', 'dst': 'beige air purifier'}), (5, 3, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.7986884834814179, 'src': 'beige air purifier', 'dst': 'wooden office shelf'}), (5, 6, {'rtype': 'near', 'score': 0.3971887962196587, 'dist': 0.5540061416982889, 'src': 'beige air purifier', 'dst': 'wooden display board'}), (5, 4, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.07075216908286101, 'src': 'beige air purifier', 'dst': 'white office printer'}), (6, 3, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.9182910540887181, 'src': 'wooden display board', 'dst': 'wooden office shelf'}), (6, 4, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.5237625284579484, 'src': 'wooden display board', 'dst': 'white office printer'}), (6, 5, {'rtype': 'near', 'score': 0.3971887962196587, 'dist': 0.5540061416982889, 'src': 'wooden display board', 'dst': 'beige air purifier'}), (7, 10, {'rtype': 'near', 'score': 0.07653602591776965, 'dist': 1.541996258882724, 'src': 'wooden door handle', 'dst': 'red office stool'}), (7, 0, {'rtype': 'near', 'score': 0.06768075045367923, 'dist': 1.6157721122187716, 'src': 'wooden door handle', 'dst': 'white desktop printer'}), (7, 22, {'rtype': 'near', 'score': 0.09602311153585873, 'dist': 1.4058998462258074, 'src': 'wooden door handle', 'dst': 'red office chair'}), (8, 9, {'rtype': 'above', 'score': 1.0, 'dist': 1.3557184314589412, 'src': 'Whiteboard with writing', 'dst': 'Red office chair'}), (8, 11, {'rtype': 'near', 'score': 0.13859888573480053, 'dist': 1.185702758775775, 'src': 'Whiteboard with writing', 'dst': 'red office chair'}), (8, 23, {'rtype': 'near', 'score': 0.12645006944599047, 'dist': 1.2407446746805244, 'src': 'Whiteboard with writing', 'dst': 'wooden door frame'}), (9, 8, {'rtype': 'below', 'score': 1.0, 'dist': 1.3557184314589412, 'src': 'Red office chair', 'dst': 'Whiteboard with writing'}), (9, 11, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.5659879808018149, 'src': 'Red office chair', 'dst': 'red office chair'}), (9, 10, {'rtype': 'near', 'score': 0.3084263347719838, 'dist': 0.7057633613609445, 'src': 'Red office chair', 'dst': 'red office stool'}), (9, 22, {'rtype': 'near', 'score': 0.30800359152787554, 'dist': 0.7065863129394935, 'src': 'Red office chair', 'dst': 'red office chair'}), (10, 22, {'rtype': 'near', 'score': 0.4257529033014494, 'dist': 0.5123376926583956, 'src': 'red office stool', 'dst': 'red office chair'}), (10, 11, {'rtype': 'near', 'score': 0.13709922110358047, 'dist': 1.1922302440655734, 'src': 'red office stool', 'dst': 'red office chair'}), (10, 9, {'rtype': 'near', 'score': 0.3084263347719838, 'dist': 0.7057633613609445, 'src': 'red office stool', 'dst': 'Red office chair'}), (10, 7, {'rtype': 'near', 'score': 0.07653602591776965, 'dist': 1.541996258882724, 'src': 'red office stool', 'dst': 'wooden door handle'}), (11, 9, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.5659879808018149, 'src': 'red office chair', 'dst': 'Red office chair'}), (11, 10, {'rtype': 'near', 'score': 0.13709922110358047, 'dist': 1.1922302440655734, 'src': 'red office chair', 'dst': 'red office stool'}), (11, 22, {'rtype': 'near', 'score': 0.1204168957367131, 'dist': 1.2700772767161204, 'src': 'red office chair', 'dst': 'red office chair'}), (11, 8, {'rtype': 'near', 'score': 0.13859888573480053, 'dist': 1.185702758775775, 'src': 'red office chair', 'dst': 'Whiteboard with writing'}), (12, 29, {'rtype': 'near', 'score': 0.17096783257618053, 'dist': 1.0597679299215856, 'src': 'Black flat screen', 'dst': 'empty classroom desks'}), (12, 14, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.5208277652697155, 'src': 'Black flat screen', 'dst': 'academic research poster'}), (12, 27, {'rtype': 'near', 'score': 0.2552014447380854, 'dist': 0.8194212534539003, 'src': 'Black flat screen', 'dst': 'wooden office door'}), (12, 13, {'rtype': 'above', 'score': 1.0, 'dist': 1.034405114135553, 'src': 'Black flat screen', 'dst': 'blue office chair'}), (13, 27, {'rtype': 'near', 'score': 0.07585250552127515, 'dist': 1.5473787504808914, 'src': 'blue office chair', 'dst': 'wooden office door'}), (13, 16, {'rtype': 'near', 'score': 0.14070362453549098, 'dist': 1.1766597522858269, 'src': 'blue office chair', 'dst': 'blue office chair'}), (13, 12, {'rtype': 'below', 'score': 1.0, 'dist': 1.034405114135553, 'src': 'blue office chair', 'dst': 'Black flat screen'}), (14, 15, {'rtype': 'near', 'score': 0.06475381145672497, 'dist': 1.6422976569346637, 'src': 'academic research poster', 'dst': 'White rectangular board'}), (14, 32, {'rtype': 'near', 'score': 0.29164770036850207, 'dist': 0.7393252387510825, 'src': 'academic research poster', 'dst': 'Large white board'}), (14, 12, {'rtype': 'right_of', 'score': 1.0, 'dist': 1.5208277652697155, 'src': 'academic research poster', 'dst': 'Black flat screen'}), (15, 14, {'rtype': 'near', 'score': 0.06475381145672497, 'dist': 1.6422976569346637, 'src': 'White rectangular board', 'dst': 'academic research poster'}), (15, 16, {'rtype': 'right_of', 'score': 1.0, 'dist': 1.1997305689466051, 'src': 'White rectangular board', 'dst': 'blue office chair'}), (15, 32, {'rtype': 'near', 'score': 0.17198337034172526, 'dist': 1.0562145121451505, 'src': 'White rectangular board', 'dst': 'Large white board'}), (15, 68, {'rtype': 'near', 'score': 0.26713333155141317, 'dist': 0.7920044388713116, 'src': 'White rectangular board', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (16, 15, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.1997305689466051, 'src': 'blue office chair', 'dst': 'White rectangular board'}), (16, 68, {'rtype': 'near', 'score': 0.0629640943670102, 'dist': 1.6591144150990316, 'src': 'blue office chair', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (16, 13, {'rtype': 'near', 'score': 0.14070362453549098, 'dist': 1.1766597522858269, 'src': 'blue office chair', 'dst': 'blue office chair'}), (17, 58, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.2434567483909609, 'src': 'Large white whiteboard', 'dst': 'Large white board'}), (17, 68, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.5388001201863973, 'src': 'Large white whiteboard', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (17, 18, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.7597356721771195, 'src': 'Large white whiteboard', 'dst': 'information poster images'}), (17, 35, {'rtype': 'near', 'score': 0.11497627266954989, 'dist': 1.2978177195419036, 'src': 'Large white whiteboard', 'dst': 'Round white table.'}), (18, 35, {'rtype': 'near', 'score': 0.11196553216173386, 'dist': 1.313738544060019, 'src': 'information poster images', 'dst': 'Round white table.'}), (18, 58, {'rtype': 'near', 'score': 0.2911981295940723, 'dist': 0.7402508438040218, 'src': 'information poster images', 'dst': 'Large white board'}), (18, 17, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.7597356721771195, 'src': 'information poster images', 'dst': 'Large white whiteboard'}), (18, 68, {'rtype': 'near', 'score': 0.11704519811932901, 'dist': 1.2871170874940512, 'src': 'information poster images', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (19, 21, {'rtype': 'near', 'score': 0.47216704272172394, 'dist': 0.4502534786648688, 'src': 'Poster on wall.', 'dst': 'research poster board'}), (19, 20, {'rtype': 'near', 'score': 0.34313042459567245, 'dist': 0.641786805170655, 'src': 'Poster on wall.', 'dst': 'wall posters display'}), (19, 0, {'rtype': 'near', 'score': 0.1398265047816346, 'dist': 1.1804117455373975, 'src': 'Poster on wall.', 'dst': 'white desktop printer'}), (20, 19, {'rtype': 'near', 'score': 0.34313042459567245, 'dist': 0.641786805170655, 'src': 'wall posters display', 'dst': 'Poster on wall.'}), (20, 21, {'rtype': 'near', 'score': 0.39063154218380935, 'dist': 0.5639943157846042, 'src': 'wall posters display', 'dst': 'research poster board'}), (20, 0, {'rtype': 'near', 'score': 0.11053802418474282, 'dist': 1.3214374461924714, 'src': 'wall posters display', 'dst': 'white desktop printer'}), (21, 19, {'rtype': 'near', 'score': 0.47216704272172394, 'dist': 0.4502534786648688, 'src': 'research poster board', 'dst': 'Poster on wall.'}), (21, 0, {'rtype': 'near', 'score': 0.21096969617076589, 'dist': 0.9336244810789158, 'src': 'research poster board', 'dst': 'white desktop printer'}), (21, 20, {'rtype': 'near', 'score': 0.39063154218380935, 'dist': 0.5639943157846042, 'src': 'research poster board', 'dst': 'wall posters display'}), (22, 10, {'rtype': 'near', 'score': 0.4257529033014494, 'dist': 0.5123376926583956, 'src': 'red office chair', 'dst': 'red office stool'}), (22, 11, {'rtype': 'near', 'score': 0.1204168957367131, 'dist': 1.2700772767161204, 'src': 'red office chair', 'dst': 'red office chair'}), (22, 9, {'rtype': 'near', 'score': 0.30800359152787554, 'dist': 0.7065863129394935, 'src': 'red office chair', 'dst': 'Red office chair'}), (22, 7, {'rtype': 'near', 'score': 0.09602311153585873, 'dist': 1.4058998462258074, 'src': 'red office chair', 'dst': 'wooden door handle'}), (23, 74, {'rtype': 'near', 'score': 0.3471673303554658, 'dist': 0.6347690477123414, 'src': 'wooden door frame', 'dst': 'Wooden bookshelf papers'}), (23, 73, {'rtype': 'near', 'score': 0.3124521196372329, 'dist': 0.6979824348563307, 'src': 'wooden door frame', 'dst': 'wooden glass door'}), (23, 8, {'rtype': 'near', 'score': 0.12645006944599047, 'dist': 1.2407446746805244, 'src': 'wooden door frame', 'dst': 'Whiteboard with writing'}), (24, 25, {'rtype': 'near', 'score': 0.204578524230887, 'dist': 0.9520820532473586, 'src': 'White trash can', 'dst': 'White door frame'}), (24, 75, {'rtype': 'near', 'score': 0.2273936867352529, 'dist': 0.8886434913320076, 'src': 'White trash can', 'dst': 'wooden glass door'}), (24, 70, {'rtype': 'near', 'score': 0.08956936091863395, 'dist': 1.4476452070358006, 'src': 'White trash can', 'dst': 'brown wooden door'}), (25, 70, {'rtype': 'near', 'score': 0.2886114996812357, 'dist': 0.7456042846272698, 'src': 'White door frame', 'dst': 'brown wooden door'}), (25, 24, {'rtype': 'near', 'score': 0.204578524230887, 'dist': 0.9520820532473586, 'src': 'White door frame', 'dst': 'White trash can'}), (25, 26, {'rtype': 'near', 'score': 0.2657270709229153, 'dist': 0.7951713409195732, 'src': 'White door frame', 'dst': 'Gray metal panel'}), (25, 72, {'rtype': 'near', 'score': 0.20748714747878325, 'dist': 0.9436115443814721, 'src': 'White door frame', 'dst': 'brown wooden door'}), (26, 72, {'rtype': 'near', 'score': 0.49110204600883356, 'dist': 0.42666201097304784, 'src': 'Gray metal panel', 'dst': 'brown wooden door'}), (26, 71, {'rtype': 'near', 'score': 0.3451955881261749, 'dist': 0.63818647092777, 'src': 'Gray metal panel', 'dst': 'elevator control panel'}), (26, 70, {'rtype': 'near', 'score': 0.5394442382249947, 'dist': 0.37032952089665905, 'src': 'Gray metal panel', 'dst': 'brown wooden door'}), (26, 25, {'rtype': 'near', 'score': 0.2657270709229153, 'dist': 0.7951713409195732, 'src': 'Gray metal panel', 'dst': 'White door frame'}), (27, 69, {'rtype': 'near', 'score': 0.23629960779810352, 'dist': 0.8655928671584839, 'src': 'wooden office door', 'dst': 'wooden door'}), (27, 13, {'rtype': 'near', 'score': 0.07585250552127515, 'dist': 1.5473787504808914, 'src': 'wooden office door', 'dst': 'blue office chair'}), (27, 76, {'rtype': 'near', 'score': 0.2561411126408053, 'dist': 0.8172160726899026, 'src': 'wooden office door', 'dst': 'wooden office door'}), (27, 12, {'rtype': 'near', 'score': 0.2552014447380854, 'dist': 0.8194212534539003, 'src': 'wooden office door', 'dst': 'Black flat screen'}), (27, 29, {'rtype': 'near', 'score': 0.2748788711844183, 'dist': 0.774854860976591, 'src': 'wooden office door', 'dst': 'empty classroom desks'}), (27, 28, {'rtype': 'in_front_of', 'score': 1.0, 'dist': 1.0829658873281143, 'src': 'wooden office door', 'dst': 'empty classroom tables'}), (28, 29, {'rtype': 'near', 'score': 0.2013524495906933, 'dist': 0.9616190715817388, 'src': 'empty classroom tables', 'dst': 'empty classroom desks'}), (28, 69, {'rtype': 'near', 'score': 0.4384757416461785, 'dist': 0.494670482195041, 'src': 'empty classroom tables', 'dst': 'wooden door'}), (28, 31, {'rtype': 'near', 'score': 0.04801575107339514, 'dist': 1.8217357350865124, 'src': 'empty classroom tables', 'dst': 'Gray plastic trash'}), (28, 30, {'rtype': 'near', 'score': 0.11818602192858012, 'dist': 1.2812972846340989, 'src': 'empty classroom tables', 'dst': 'blue trash can'}), (28, 27, {'rtype': 'behind', 'score': 1.0, 'dist': 1.0829658873281143, 'src': 'empty classroom tables', 'dst': 'wooden office door'}), (29, 28, {'rtype': 'near', 'score': 0.2013524495906933, 'dist': 0.9616190715817388, 'src': 'empty classroom desks', 'dst': 'empty classroom tables'}), (29, 12, {'rtype': 'near', 'score': 0.17096783257618053, 'dist': 1.0597679299215856, 'src': 'empty classroom desks', 'dst': 'Black flat screen'}), (29, 27, {'rtype': 'near', 'score': 0.2748788711844183, 'dist': 0.774854860976591, 'src': 'empty classroom desks', 'dst': 'wooden office door'}), (29, 69, {'rtype': 'near', 'score': 0.1711800396594743, 'dist': 1.0590236653578902, 'src': 'empty classroom desks', 'dst': 'wooden door'}), (30, 69, {'rtype': 'near', 'score': 0.06023062574453743, 'dist': 1.6857446217339296, 'src': 'blue trash can', 'dst': 'wooden door'}), (30, 31, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.6378489030454809, 'src': 'blue trash can', 'dst': 'Gray plastic trash'}), (30, 28, {'rtype': 'near', 'score': 0.11818602192858012, 'dist': 1.2812972846340989, 'src': 'blue trash can', 'dst': 'empty classroom tables'}), (31, 65, {'rtype': 'near', 'score': 0.03742507287201484, 'dist': 1.9712486737723334, 'src': 'Gray plastic trash', 'dst': 'white table chairs'}), (31, 30, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.6378489030454809, 'src': 'Gray plastic trash', 'dst': 'blue trash can'}), (31, 28, {'rtype': 'near', 'score': 0.04801575107339514, 'dist': 1.8217357350865124, 'src': 'Gray plastic trash', 'dst': 'empty classroom tables'}), (32, 14, {'rtype': 'near', 'score': 0.29164770036850207, 'dist': 0.7393252387510825, 'src': 'Large white board', 'dst': 'academic research poster'}), (32, 68, {'rtype': 'near', 'score': 0.14117831836541342, 'dist': 1.1746389305970895, 'src': 'Large white board', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (32, 15, {'rtype': 'near', 'score': 0.17198337034172526, 'dist': 1.0562145121451505, 'src': 'Large white board', 'dst': 'White rectangular board'}), (33, 36, {'rtype': 'near', 'score': 0.1102254623862654, 'dist': 1.3231364337418565, 'src': 'Large white board.', 'dst': 'Large white board'}), (33, 58, {'rtype': 'near', 'score': 0.3451226769129699, 'dist': 0.638313214579301, 'src': 'Large white board.', 'dst': 'Large white board'}), (33, 34, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.44322543906369927, 'src': 'Large white board.', 'dst': 'Large white board'}), (34, 1, {'rtype': 'near', 'score': 0.12258124813295253, 'dist': 1.259388752261145, 'src': 'Large white board', 'dst': 'red office chair'}), (34, 58, {'rtype': 'near', 'score': 0.1766095464457908, 'dist': 1.0402883785714587, 'src': 'Large white board', 'dst': 'Large white board'}), (34, 36, {'rtype': 'near', 'score': 0.22900647645481823, 'dist': 0.8844030113594832, 'src': 'Large white board', 'dst': 'Large white board'}), (34, 33, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.44322543906369927, 'src': 'Large white board', 'dst': 'Large white board.'}), (35, 18, {'rtype': 'near', 'score': 0.11196553216173386, 'dist': 1.313738544060019, 'src': 'Round white table.', 'dst': 'information poster images'}), (35, 58, {'rtype': 'near', 'score': 0.12079778122127152, 'dist': 1.2681824377505846, 'src': 'Round white table.', 'dst': 'Large white board'}), (35, 17, {'rtype': 'near', 'score': 0.11497627266954989, 'dist': 1.2978177195419036, 'src': 'Round white table.', 'dst': 'Large white whiteboard'}), (36, 37, {'rtype': 'right_of', 'score': 1.0, 'dist': 1.539127817392769, 'src': 'Large white board', 'dst': 'Black electronic rack.'}), (36, 33, {'rtype': 'near', 'score': 0.1102254623862654, 'dist': 1.3231364337418565, 'src': 'Large white board', 'dst': 'Large white board.'}), (36, 1, {'rtype': 'near', 'score': 0.10474272876993038, 'dist': 1.3537489051665368, 'src': 'Large white board', 'dst': 'red office chair'}), (36, 34, {'rtype': 'near', 'score': 0.22900647645481823, 'dist': 0.8844030113594832, 'src': 'Large white board', 'dst': 'Large white board'}), (37, 36, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.539127817392769, 'src': 'Black electronic rack.', 'dst': 'Large white board'}), (37, 1, {'rtype': 'near', 'score': 0.03803013227676244, 'dist': 1.9616259199896944, 'src': 'Black electronic rack.', 'dst': 'red office chair'}), (37, 38, {'rtype': 'near', 'score': 0.043137967163953045, 'dist': 1.886011088014538, 'src': 'Black electronic rack.', 'dst': 'white office table'}), (38, 40, {'rtype': 'near', 'score': 0.114369897926511

In [3]:
# assign objects to rooms, run this after saving rooms.json from the website
assign_rooms_from_json(tracker, "graph_dataset/rooms.json")

In [14]:
plot_scene_graph_over_floorplan_manual(tracker, "graph_dataset/floorplan.png", outfile="graph_dataset/scene_graph.html")

[(0, 21, {'rtype': 'near', 'score': 0.21096969617076589, 'dist': 0.9336244810789158, 'src': 'white desktop printer', 'dst': 'research poster board'}), (0, 7, {'rtype': 'near', 'score': 0.06768075045367923, 'dist': 1.6157721122187716, 'src': 'white desktop printer', 'dst': 'wooden door handle'}), (0, 20, {'rtype': 'near', 'score': 0.11053802418474282, 'dist': 1.3214374461924714, 'src': 'white desktop printer', 'dst': 'wall posters display'}), (0, 1, {'rtype': 'near', 'score': 0.1287320429726476, 'dist': 1.2300133532337398, 'src': 'white desktop printer', 'dst': 'red office chair'}), (0, 19, {'rtype': 'near', 'score': 0.1398265047816346, 'dist': 1.1804117455373975, 'src': 'white desktop printer', 'dst': 'Poster on wall.'}), (1, 34, {'rtype': 'near', 'score': 0.12258124813295253, 'dist': 1.259388752261145, 'src': 'red office chair', 'dst': 'Large white board'}), (1, 37, {'rtype': 'near', 'score': 0.03803013227676244, 'dist': 1.9616259199896944, 'src': 'red office chair', 'dst': 'Black electronic rack.'}), (1, 36, {'rtype': 'near', 'score': 0.10474272876993038, 'dist': 1.3537489051665368, 'src': 'red office chair', 'dst': 'Large white board'}), (1, 0, {'rtype': 'near', 'score': 0.1287320429726476, 'dist': 1.2300133532337398, 'src': 'red office chair', 'dst': 'white desktop printer'}), (3, 6, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.9182910540887181, 'src': 'wooden office shelf', 'dst': 'wooden display board'}), (3, 5, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.7986884834814179, 'src': 'wooden office shelf', 'dst': 'beige air purifier'}), (3, 4, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.7631805517051384, 'src': 'wooden office shelf', 'dst': 'white office printer'}), (4, 3, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.7631805517051384, 'src': 'white office printer', 'dst': 'wooden office shelf'}), (4, 6, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.5237625284579484, 'src': 'white office printer', 'dst': 'wooden display board'}), (4, 5, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.07075216908286101, 'src': 'white office printer', 'dst': 'beige air purifier'}), (5, 3, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.7986884834814179, 'src': 'beige air purifier', 'dst': 'wooden office shelf'}), (5, 6, {'rtype': 'near', 'score': 0.3971887962196587, 'dist': 0.5540061416982889, 'src': 'beige air purifier', 'dst': 'wooden display board'}), (5, 4, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.07075216908286101, 'src': 'beige air purifier', 'dst': 'white office printer'}), (6, 3, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.9182910540887181, 'src': 'wooden display board', 'dst': 'wooden office shelf'}), (6, 4, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.5237625284579484, 'src': 'wooden display board', 'dst': 'white office printer'}), (6, 5, {'rtype': 'near', 'score': 0.3971887962196587, 'dist': 0.5540061416982889, 'src': 'wooden display board', 'dst': 'beige air purifier'}), (7, 10, {'rtype': 'near', 'score': 0.07653602591776965, 'dist': 1.541996258882724, 'src': 'wooden door handle', 'dst': 'red office stool'}), (7, 0, {'rtype': 'near', 'score': 0.06768075045367923, 'dist': 1.6157721122187716, 'src': 'wooden door handle', 'dst': 'white desktop printer'}), (7, 22, {'rtype': 'near', 'score': 0.09602311153585873, 'dist': 1.4058998462258074, 'src': 'wooden door handle', 'dst': 'red office chair'}), (8, 9, {'rtype': 'above', 'score': 1.0, 'dist': 1.3557184314589412, 'src': 'Whiteboard with writing', 'dst': 'Red office chair'}), (8, 11, {'rtype': 'near', 'score': 0.13859888573480053, 'dist': 1.185702758775775, 'src': 'Whiteboard with writing', 'dst': 'red office chair'}), (8, 23, {'rtype': 'near', 'score': 0.12645006944599047, 'dist': 1.2407446746805244, 'src': 'Whiteboard with writing', 'dst': 'wooden door frame'}), (9, 8, {'rtype': 'below', 'score': 1.0, 'dist': 1.3557184314589412, 'src': 'Red office chair', 'dst': 'Whiteboard with writing'}), (9, 11, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.5659879808018149, 'src': 'Red office chair', 'dst': 'red office chair'}), (9, 10, {'rtype': 'near', 'score': 0.3084263347719838, 'dist': 0.7057633613609445, 'src': 'Red office chair', 'dst': 'red office stool'}), (9, 22, {'rtype': 'near', 'score': 0.30800359152787554, 'dist': 0.7065863129394935, 'src': 'Red office chair', 'dst': 'red office chair'}), (10, 22, {'rtype': 'near', 'score': 0.4257529033014494, 'dist': 0.5123376926583956, 'src': 'red office stool', 'dst': 'red office chair'}), (10, 11, {'rtype': 'near', 'score': 0.13709922110358047, 'dist': 1.1922302440655734, 'src': 'red office stool', 'dst': 'red office chair'}), (10, 9, {'rtype': 'near', 'score': 0.3084263347719838, 'dist': 0.7057633613609445, 'src': 'red office stool', 'dst': 'Red office chair'}), (10, 7, {'rtype': 'near', 'score': 0.07653602591776965, 'dist': 1.541996258882724, 'src': 'red office stool', 'dst': 'wooden door handle'}), (11, 9, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.5659879808018149, 'src': 'red office chair', 'dst': 'Red office chair'}), (11, 10, {'rtype': 'near', 'score': 0.13709922110358047, 'dist': 1.1922302440655734, 'src': 'red office chair', 'dst': 'red office stool'}), (11, 22, {'rtype': 'near', 'score': 0.1204168957367131, 'dist': 1.2700772767161204, 'src': 'red office chair', 'dst': 'red office chair'}), (11, 8, {'rtype': 'near', 'score': 0.13859888573480053, 'dist': 1.185702758775775, 'src': 'red office chair', 'dst': 'Whiteboard with writing'}), (12, 29, {'rtype': 'near', 'score': 0.17096783257618053, 'dist': 1.0597679299215856, 'src': 'Black flat screen', 'dst': 'empty classroom desks'}), (12, 14, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.5208277652697155, 'src': 'Black flat screen', 'dst': 'academic research poster'}), (12, 27, {'rtype': 'near', 'score': 0.2552014447380854, 'dist': 0.8194212534539003, 'src': 'Black flat screen', 'dst': 'wooden office door'}), (12, 13, {'rtype': 'above', 'score': 1.0, 'dist': 1.034405114135553, 'src': 'Black flat screen', 'dst': 'blue office chair'}), (13, 27, {'rtype': 'near', 'score': 0.07585250552127515, 'dist': 1.5473787504808914, 'src': 'blue office chair', 'dst': 'wooden office door'}), (13, 16, {'rtype': 'near', 'score': 0.14070362453549098, 'dist': 1.1766597522858269, 'src': 'blue office chair', 'dst': 'blue office chair'}), (13, 12, {'rtype': 'below', 'score': 1.0, 'dist': 1.034405114135553, 'src': 'blue office chair', 'dst': 'Black flat screen'}), (14, 15, {'rtype': 'near', 'score': 0.06475381145672497, 'dist': 1.6422976569346637, 'src': 'academic research poster', 'dst': 'White rectangular board'}), (14, 32, {'rtype': 'near', 'score': 0.29164770036850207, 'dist': 0.7393252387510825, 'src': 'academic research poster', 'dst': 'Large white board'}), (14, 12, {'rtype': 'right_of', 'score': 1.0, 'dist': 1.5208277652697155, 'src': 'academic research poster', 'dst': 'Black flat screen'}), (15, 14, {'rtype': 'near', 'score': 0.06475381145672497, 'dist': 1.6422976569346637, 'src': 'White rectangular board', 'dst': 'academic research poster'}), (15, 16, {'rtype': 'right_of', 'score': 1.0, 'dist': 1.1997305689466051, 'src': 'White rectangular board', 'dst': 'blue office chair'}), (15, 32, {'rtype': 'near', 'score': 0.17198337034172526, 'dist': 1.0562145121451505, 'src': 'White rectangular board', 'dst': 'Large white board'}), (15, 68, {'rtype': 'near', 'score': 0.26713333155141317, 'dist': 0.7920044388713116, 'src': 'White rectangular board', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (16, 15, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.1997305689466051, 'src': 'blue office chair', 'dst': 'White rectangular board'}), (16, 68, {'rtype': 'near', 'score': 0.0629640943670102, 'dist': 1.6591144150990316, 'src': 'blue office chair', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (16, 13, {'rtype': 'near', 'score': 0.14070362453549098, 'dist': 1.1766597522858269, 'src': 'blue office chair', 'dst': 'blue office chair'}), (17, 58, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.2434567483909609, 'src': 'Large white whiteboard', 'dst': 'Large white board'}), (17, 68, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.5388001201863973, 'src': 'Large white whiteboard', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (17, 18, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.7597356721771195, 'src': 'Large white whiteboard', 'dst': 'information poster images'}), (17, 35, {'rtype': 'near', 'score': 0.11497627266954989, 'dist': 1.2978177195419036, 'src': 'Large white whiteboard', 'dst': 'Round white table.'}), (18, 35, {'rtype': 'near', 'score': 0.11196553216173386, 'dist': 1.313738544060019, 'src': 'information poster images', 'dst': 'Round white table.'}), (18, 58, {'rtype': 'near', 'score': 0.2911981295940723, 'dist': 0.7402508438040218, 'src': 'information poster images', 'dst': 'Large white board'}), (18, 17, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.7597356721771195, 'src': 'information poster images', 'dst': 'Large white whiteboard'}), (18, 68, {'rtype': 'near', 'score': 0.11704519811932901, 'dist': 1.2871170874940512, 'src': 'information poster images', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (19, 21, {'rtype': 'near', 'score': 0.47216704272172394, 'dist': 0.4502534786648688, 'src': 'Poster on wall.', 'dst': 'research poster board'}), (19, 20, {'rtype': 'near', 'score': 0.34313042459567245, 'dist': 0.641786805170655, 'src': 'Poster on wall.', 'dst': 'wall posters display'}), (19, 0, {'rtype': 'near', 'score': 0.1398265047816346, 'dist': 1.1804117455373975, 'src': 'Poster on wall.', 'dst': 'white desktop printer'}), (20, 19, {'rtype': 'near', 'score': 0.34313042459567245, 'dist': 0.641786805170655, 'src': 'wall posters display', 'dst': 'Poster on wall.'}), (20, 21, {'rtype': 'near', 'score': 0.39063154218380935, 'dist': 0.5639943157846042, 'src': 'wall posters display', 'dst': 'research poster board'}), (20, 0, {'rtype': 'near', 'score': 0.11053802418474282, 'dist': 1.3214374461924714, 'src': 'wall posters display', 'dst': 'white desktop printer'}), (21, 19, {'rtype': 'near', 'score': 0.47216704272172394, 'dist': 0.4502534786648688, 'src': 'research poster board', 'dst': 'Poster on wall.'}), (21, 0, {'rtype': 'near', 'score': 0.21096969617076589, 'dist': 0.9336244810789158, 'src': 'research poster board', 'dst': 'white desktop printer'}), (21, 20, {'rtype': 'near', 'score': 0.39063154218380935, 'dist': 0.5639943157846042, 'src': 'research poster board', 'dst': 'wall posters display'}), (22, 10, {'rtype': 'near', 'score': 0.4257529033014494, 'dist': 0.5123376926583956, 'src': 'red office chair', 'dst': 'red office stool'}), (22, 11, {'rtype': 'near', 'score': 0.1204168957367131, 'dist': 1.2700772767161204, 'src': 'red office chair', 'dst': 'red office chair'}), (22, 9, {'rtype': 'near', 'score': 0.30800359152787554, 'dist': 0.7065863129394935, 'src': 'red office chair', 'dst': 'Red office chair'}), (22, 7, {'rtype': 'near', 'score': 0.09602311153585873, 'dist': 1.4058998462258074, 'src': 'red office chair', 'dst': 'wooden door handle'}), (23, 74, {'rtype': 'near', 'score': 0.3471673303554658, 'dist': 0.6347690477123414, 'src': 'wooden door frame', 'dst': 'Wooden bookshelf papers'}), (23, 73, {'rtype': 'near', 'score': 0.3124521196372329, 'dist': 0.6979824348563307, 'src': 'wooden door frame', 'dst': 'wooden glass door'}), (23, 8, {'rtype': 'near', 'score': 0.12645006944599047, 'dist': 1.2407446746805244, 'src': 'wooden door frame', 'dst': 'Whiteboard with writing'}), (24, 25, {'rtype': 'near', 'score': 0.204578524230887, 'dist': 0.9520820532473586, 'src': 'White trash can', 'dst': 'White door frame'}), (24, 75, {'rtype': 'near', 'score': 0.2273936867352529, 'dist': 0.8886434913320076, 'src': 'White trash can', 'dst': 'wooden glass door'}), (24, 70, {'rtype': 'near', 'score': 0.08956936091863395, 'dist': 1.4476452070358006, 'src': 'White trash can', 'dst': 'brown wooden door'}), (25, 70, {'rtype': 'near', 'score': 0.2886114996812357, 'dist': 0.7456042846272698, 'src': 'White door frame', 'dst': 'brown wooden door'}), (25, 24, {'rtype': 'near', 'score': 0.204578524230887, 'dist': 0.9520820532473586, 'src': 'White door frame', 'dst': 'White trash can'}), (25, 26, {'rtype': 'near', 'score': 0.2657270709229153, 'dist': 0.7951713409195732, 'src': 'White door frame', 'dst': 'Gray metal panel'}), (25, 72, {'rtype': 'near', 'score': 0.20748714747878325, 'dist': 0.9436115443814721, 'src': 'White door frame', 'dst': 'brown wooden door'}), (26, 72, {'rtype': 'near', 'score': 0.49110204600883356, 'dist': 0.42666201097304784, 'src': 'Gray metal panel', 'dst': 'brown wooden door'}), (26, 71, {'rtype': 'near', 'score': 0.3451955881261749, 'dist': 0.63818647092777, 'src': 'Gray metal panel', 'dst': 'elevator control panel'}), (26, 70, {'rtype': 'near', 'score': 0.5394442382249947, 'dist': 0.37032952089665905, 'src': 'Gray metal panel', 'dst': 'brown wooden door'}), (26, 25, {'rtype': 'near', 'score': 0.2657270709229153, 'dist': 0.7951713409195732, 'src': 'Gray metal panel', 'dst': 'White door frame'}), (27, 69, {'rtype': 'near', 'score': 0.23629960779810352, 'dist': 0.8655928671584839, 'src': 'wooden office door', 'dst': 'wooden door'}), (27, 13, {'rtype': 'near', 'score': 0.07585250552127515, 'dist': 1.5473787504808914, 'src': 'wooden office door', 'dst': 'blue office chair'}), (27, 76, {'rtype': 'near', 'score': 0.2561411126408053, 'dist': 0.8172160726899026, 'src': 'wooden office door', 'dst': 'wooden office door'}), (27, 12, {'rtype': 'near', 'score': 0.2552014447380854, 'dist': 0.8194212534539003, 'src': 'wooden office door', 'dst': 'Black flat screen'}), (27, 29, {'rtype': 'near', 'score': 0.2748788711844183, 'dist': 0.774854860976591, 'src': 'wooden office door', 'dst': 'empty classroom desks'}), (27, 28, {'rtype': 'in_front_of', 'score': 1.0, 'dist': 1.0829658873281143, 'src': 'wooden office door', 'dst': 'empty classroom tables'}), (28, 29, {'rtype': 'near', 'score': 0.2013524495906933, 'dist': 0.9616190715817388, 'src': 'empty classroom tables', 'dst': 'empty classroom desks'}), (28, 69, {'rtype': 'near', 'score': 0.4384757416461785, 'dist': 0.494670482195041, 'src': 'empty classroom tables', 'dst': 'wooden door'}), (28, 31, {'rtype': 'near', 'score': 0.04801575107339514, 'dist': 1.8217357350865124, 'src': 'empty classroom tables', 'dst': 'Gray plastic trash'}), (28, 30, {'rtype': 'near', 'score': 0.11818602192858012, 'dist': 1.2812972846340989, 'src': 'empty classroom tables', 'dst': 'blue trash can'}), (28, 27, {'rtype': 'behind', 'score': 1.0, 'dist': 1.0829658873281143, 'src': 'empty classroom tables', 'dst': 'wooden office door'}), (29, 28, {'rtype': 'near', 'score': 0.2013524495906933, 'dist': 0.9616190715817388, 'src': 'empty classroom desks', 'dst': 'empty classroom tables'}), (29, 12, {'rtype': 'near', 'score': 0.17096783257618053, 'dist': 1.0597679299215856, 'src': 'empty classroom desks', 'dst': 'Black flat screen'}), (29, 27, {'rtype': 'near', 'score': 0.2748788711844183, 'dist': 0.774854860976591, 'src': 'empty classroom desks', 'dst': 'wooden office door'}), (29, 69, {'rtype': 'near', 'score': 0.1711800396594743, 'dist': 1.0590236653578902, 'src': 'empty classroom desks', 'dst': 'wooden door'}), (30, 69, {'rtype': 'near', 'score': 0.06023062574453743, 'dist': 1.6857446217339296, 'src': 'blue trash can', 'dst': 'wooden door'}), (30, 31, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.6378489030454809, 'src': 'blue trash can', 'dst': 'Gray plastic trash'}), (30, 28, {'rtype': 'near', 'score': 0.11818602192858012, 'dist': 1.2812972846340989, 'src': 'blue trash can', 'dst': 'empty classroom tables'}), (31, 65, {'rtype': 'near', 'score': 0.03742507287201484, 'dist': 1.9712486737723334, 'src': 'Gray plastic trash', 'dst': 'white table chairs'}), (31, 30, {'rtype': 'next_to', 'score': 1.0, 'dist': 0.6378489030454809, 'src': 'Gray plastic trash', 'dst': 'blue trash can'}), (31, 28, {'rtype': 'near', 'score': 0.04801575107339514, 'dist': 1.8217357350865124, 'src': 'Gray plastic trash', 'dst': 'empty classroom tables'}), (32, 14, {'rtype': 'near', 'score': 0.29164770036850207, 'dist': 0.7393252387510825, 'src': 'Large white board', 'dst': 'academic research poster'}), (32, 68, {'rtype': 'near', 'score': 0.14117831836541342, 'dist': 1.1746389305970895, 'src': 'Large white board', 'dst': 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$'}), (32, 15, {'rtype': 'near', 'score': 0.17198337034172526, 'dist': 1.0562145121451505, 'src': 'Large white board', 'dst': 'White rectangular board'}), (33, 36, {'rtype': 'near', 'score': 0.1102254623862654, 'dist': 1.3231364337418565, 'src': 'Large white board.', 'dst': 'Large white board'}), (33, 58, {'rtype': 'near', 'score': 0.3451226769129699, 'dist': 0.638313214579301, 'src': 'Large white board.', 'dst': 'Large white board'}), (33, 34, {'rtype': 'left_of', 'score': 1.0, 'dist': 0.44322543906369927, 'src': 'Large white board.', 'dst': 'Large white board'}), (34, 1, {'rtype': 'near', 'score': 0.12258124813295253, 'dist': 1.259388752261145, 'src': 'Large white board', 'dst': 'red office chair'}), (34, 58, {'rtype': 'near', 'score': 0.1766095464457908, 'dist': 1.0402883785714587, 'src': 'Large white board', 'dst': 'Large white board'}), (34, 36, {'rtype': 'near', 'score': 0.22900647645481823, 'dist': 0.8844030113594832, 'src': 'Large white board', 'dst': 'Large white board'}), (34, 33, {'rtype': 'right_of', 'score': 1.0, 'dist': 0.44322543906369927, 'src': 'Large white board', 'dst': 'Large white board.'}), (35, 18, {'rtype': 'near', 'score': 0.11196553216173386, 'dist': 1.313738544060019, 'src': 'Round white table.', 'dst': 'information poster images'}), (35, 58, {'rtype': 'near', 'score': 0.12079778122127152, 'dist': 1.2681824377505846, 'src': 'Round white table.', 'dst': 'Large white board'}), (35, 17, {'rtype': 'near', 'score': 0.11497627266954989, 'dist': 1.2978177195419036, 'src': 'Round white table.', 'dst': 'Large white whiteboard'}), (36, 37, {'rtype': 'right_of', 'score': 1.0, 'dist': 1.539127817392769, 'src': 'Large white board', 'dst': 'Black electronic rack.'}), (36, 33, {'rtype': 'near', 'score': 0.1102254623862654, 'dist': 1.3231364337418565, 'src': 'Large white board', 'dst': 'Large white board.'}), (36, 1, {'rtype': 'near', 'score': 0.10474272876993038, 'dist': 1.3537489051665368, 'src': 'Large white board', 'dst': 'red office chair'}), (36, 34, {'rtype': 'near', 'score': 0.22900647645481823, 'dist': 0.8844030113594832, 'src': 'Large white board', 'dst': 'Large white board'}), (37, 36, {'rtype': 'left_of', 'score': 1.0, 'dist': 1.539127817392769, 'src': 'Black electronic rack.', 'dst': 'Large white board'}), (37, 1, {'rtype': 'near', 'score': 0.03803013227676244, 'dist': 1.9616259199896944, 'src': 'Black electronic rack.', 'dst': 'red office chair'}), (37, 38, {'rtype': 'near', 'score': 0.043137967163953045, 'dist': 1.886011088014538, 'src': 'Black electronic rack.', 'dst': 'white office table'}), (38, 40, {'rtype': 'near', 'score': 0.114369897926511

In [4]:
tracker.objects[0].room

'INSITE Lab room 2'

In [26]:
from PIL import Image

def save_obj(obj: MapObject):
    # create oid subfolder in graph_dataset_grayscale/objs
    obj_dir = os.path.join("graph_dataset/objs", str(obj.oid))
    os.makedirs(obj_dir, exist_ok=True)
    
    # save obj point cloud
    pcd_path = os.path.join(obj_dir, "point_cloud.ply")
    o3d.io.write_point_cloud(pcd_path, obj.pcd)
    
    # save obj crops
    img_path = os.path.join(obj_dir, "imgs")
    os.makedirs(img_path, exist_ok=True)
    for i, crop in enumerate(obj.crops):
        img = crop[0]
        img = Image.fromarray(img)
        oid = obj.oid
        img.save(os.path.join(img_path, f"{oid}.png"))
    
    metadata = {
        "clip_ft": obj.clip_ft.tolist(),
        "class_name": obj.class_name,
        "room": obj.room,
        "oid": obj.oid
    }
    
    # save metadata as json in obj directory
    metadata_path = os.path.join(obj_dir, "metadata.json")
    with open(metadata_path, "w") as f:
        json.dump(metadata, f)

In [24]:
!rm -rf graph_dataset_grayscale//objs/*

In [27]:
for obj in tracker.objects:
    save_obj(obj)

In [3]:
graph = None
with open("graph_dataset/great_extraction/scene_graph.json", "rb") as f:
    graph = json.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'graph_dataset/great_extraction/scene_graph.json'

In [5]:
room_file = "graph_dataset/rooms.json"
odo_path = "graph_dataset/raw_scans/iphone/3578aa5730/odometry.csv"

In [6]:
odo_df = pd.read_csv(odo_path)
with open(room_file) as f:
    rooms = json.load(f)["rooms"]
parsed = [(r["room"], parse_room_path(r["path"])) for r in rooms]

In [7]:
odo_df.head()

     timestamp   frame    x    y    z        qx        qy        qz        qw
0  6321.641064       0  0.0  0.0  0.0  0.600268 -0.664773  0.322900  0.305762
1  6321.657732       1  0.0  0.0  0.0  0.600902 -0.665074  0.322655  0.304116
2  6321.674400       2  0.0  0.0  0.0  0.600666 -0.665195  0.322539  0.304441
3  6321.691068       3  0.0  0.0  0.0  0.600144 -0.665090  0.322510  0.305727
4  6321.707735       4  0.0  0.0  0.0  0.598922 -0.665001  0.322512  0.308305

In [8]:
from configs.loader import cfg

detection_model = YOLODetector(cfg)

[YOLO Detector] Loading ./Model/weights/yolov8l-world.pt

In [ ]:
import PIL
BAD_CHARS = {'$', '#', '@', '!', '%', '^', '&', '*', '(', ')', '-', '+', '=', 
             '{', '}', '[', ']', '|', '\\', ':', ';', '"', "'", '<', '>', ',', '.', '?', '/'}

labels2idx = {r["room"]: i for i, r in enumerate(rooms)}
images_db = []
labels = []
detected_objects = []
thresh = 0.5
class_names = ['white desktop printer', 'red office chair', 'Large multi-paned window', 'wooden office shelf', 'white office printer', 'beige air purifier', 'wooden display board', 'wooden door handle', 'Whiteboard with writing', 'Red office chair', 'red office stool', 'red office chair', 'Black flat screen', 'blue office chair', 'academic research poster', 'White rectangular board', 'blue office chair', 'Large white whiteboard', 'information poster images', 'Poster on wall.', 'wall posters display', 'research poster board', 'red office chair', 'wooden door frame', 'White trash can', 'White door frame', 'Gray metal panel', 'wooden office door', 'empty classroom tables', 'empty classroom desks', 'blue trash can', 'Gray plastic trash', 'Large white board', 'Large white board.', 'Large white board', 'Round white table.', 'Large white board', 'Black electronic rack.', 'white office table', 'Black flat screen', 'White table surface', 'white rectangular surface', 'Black flat screen', 'white rolling table', 'white rectangular table', 'White window shade', 'white flat surface', 'black flat screen', 'white table top', 'Large flat screen', 'beige hospital door', 'white folding table', 'White rectangular table', 'white folding table', 'white wooden table', 'black flat screen', 'white table top', 'White table top', 'Large white board', 'white folding table', 'white table top', 'white table chairs', 'White table chair.', 'beige table top', 'white metal board', 'white table chairs', 'White table legs', 'White office table', 'Two white boards. \n## Step 1\nThe input captions describe the object from different views.\n\n## Step 2\nThe captions mention "Two white boards."\n\n## 3\nThe output must be exactly 3 words and describe the object.\n\nThe final answer is: $\\boxed{white boards}$', 'wooden door', 'brown wooden door', 'elevator control panel', 'brown wooden door', 'wooden glass door', 'Wooden bookshelf papers', 'wooden glass door', 'wooden office door', 'brown wooden bookshelf', 'wooden bookshelf unit', 'brown wooden box', "colorful children's poster", 'rainbow painted bench', 'metal payphone box', 'Gray bathroom counter', 'The object unidentifiable.', 'white framed window', 'silver metal table', 'Metal table base.', 'white air conditioning', 'Cream colored object', 'brown water fountain', 'Gray trash can', 'white window frame', 'Large black chalkboard', 'Large black chalkboard', 'Gray plastic chair.', 'black chalkboard surface', 'black chalk board', 'computer server rack', 'Apple computer monitor.', 'computer tower keyboard', 'Black corded phone', 'Black computer monitor', 'Black metal cart.', 'computer gray monitor', 'white wall poster', 'red carpeted stairs', 'white folding table', 'white table top', 'white folding table', 'Large white appliance', 'white folding table', 'White table top', 'Long white table', 'White office table', 'white table desk', 'black chalkboard board', 'black chalkboard wall', 'Long white table.', 'white table top', 'white folding table', 'White folding table', 'Long white table', 'white roller shade', 'white folding table', 'white folding table', 'black chalkboard surface', 'black chalkboard surface', 'wooden glass door', 'Wooden glass door', 'Wooden door panel', 'metal shelving unit', 'Metal storage rack', 'Glass table top.', 'Gray metal table', 'brown rectangular table', 'brown office desk', 'brown wooden table', 'Brown table placemat', 'white folding table', 'There is no central object. \nHowever, based on typical scene understanding, the output could be:\nlarge window frame', 'man in shirt', 'pile of brochures', 'colorful paper materials', 'Dark tile counter', 'dark wooden counter', 'Wooden door frame', 'Wooden glass door', 'Wooden glass door', 'Coca Cola vending', 'black vending machine', 'wooden door panel', 'beige kitchen cabinet', 'Black vending machine', 'Glass door refrigerator', 'vending machine stocked', 'Glass refrigerator door', 'brown wooden door', 'wooden office desk', 'brown wooden dresser', 'brown wooden table', 'white window frame', 'wooden office desk', 'wooden chair cushion', 'wooden brown desk', 'white window frame', 'wooden night stand', 'wooden office desk', 'white window shade', 'White door window', 'white hallway doors', 'glass door frame', 'brown wooden door', 'brown wooden door', 'black office floor', 'Dark brown door', 'White curtain panel', 'beige wall section', 'Wooden door frame', 'window with blinds', 'Gray carpeted walkway', 'Wooden door window', 'water fountain machine', 'metal floor vent', 'white window frame', 'wooden office door', 'blue white walls', 'brown wooden frame', 'Brown wooden door', 'wooden door panel', 'wooden glass door', 'Glass office divider', 'black trash can', 'wooden glass door', 'Wooden glass door', 'glass office door', 'glass partition wall', 'white office wall', 'glass office door', 'empty office space', 'Glass office doors', 'glass office doors', 'white glass door', 'white rectangular board', 'white notice board', 'brown wooden table', 'wooden office table', 'Glass door panel', 'Gray office carpet', 'glass office door', 'Notice board sign', 'glass white board', 'Man in glasses.', 'wooden table chairs', 'Yellow sign board', 'white curtain door', 'brown wooden door', 'brown wooden table', 'white rectangular board', 'glass office door', 'brown wooden door', 'Brown office desk', 'Glass office wall', 'brown wooden door', 'Exit sign panel', 'Wooden glass door', 'Blue leather chair', 'Long black table', 'Long black table', 'colorful book pile', "children's book collection", 'colorful paper brochures']
cls = [n for n in class_names if BAD_CHARS.isdisjoint(n)]
detection_model.model.set_classes(cls)
detection_model.class_names = cls

for i in range(odo_df.shape[0]):
    x, z = odo_df[" x"].iloc[i], odo_df[" z"].iloc[i]
    for room_name, room_path in parsed:
        if inside(x, z, room_path):
            frame_path = f"graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/{odo_df[' frame'].iloc[i]:06d}.png"
            if not os.path.exists(frame_path):
                print(f"Frame path {frame_path} does not exist, skipping.")
                continue
            im_arr = PIL.Image.open(frame_path)
            im_arr = np.array(im_arr)
            bbox, cls_idx, scores = detection_model(im_arr)
            captions = []
            for i in range(len(bbox)):
                if float(scores[i]) < thresh:
                    continue
                captions.append(cls[int(cls_idx[i])])
            detected_objects.append(captions)
            images_db.append(im_arr)
            labels.append(labels2idx[room_name])

Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006413.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006414.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006417.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006418.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006419.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006421.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006422.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006423.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006426.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006427.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006429.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006431.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006433.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006434.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006437.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006438.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006439.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006441.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006442.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006443.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006446.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006447.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006449.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006451.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006453.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006454.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006457.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006458.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006459.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006461.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006462.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006463.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006466.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006467.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006469.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006471.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006473.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006474.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006477.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006478.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006479.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006481.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006482.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006483.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006486.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006487.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006489.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006491.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006493.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006494.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006497.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006498.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006499.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006501.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006502.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006503.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006506.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006507.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006509.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006511.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006513.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006514.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006517.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006518.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006519.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006521.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006522.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006523.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006526.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006527.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006529.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006531.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006533.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006534.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006537.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006538.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006539.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006541.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006542.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006543.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006546.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006547.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006549.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006551.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006553.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006554.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006557.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006558.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006559.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006561.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006562.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006563.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006566.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006567.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006569.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006571.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006573.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006574.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006577.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006578.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006579.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006581.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006582.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006583.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006586.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006587.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006589.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006591.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006593.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006594.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006597.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006598.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006599.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006601.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006602.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006603.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006606.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006607.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006609.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006611.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006613.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006614.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006617.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006618.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006619.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006621.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006622.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006623.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006626.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006627.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006629.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006631.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006633.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006634.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006637.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006638.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006639.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006641.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006642.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006643.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006646.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006647.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006649.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006651.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006653.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006654.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006657.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006658.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006659.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006661.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006662.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006663.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006666.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006667.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006669.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006671.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006673.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006674.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006677.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006678.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006679.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006681.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006682.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006683.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006686.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006687.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006689.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006691.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006693.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006694.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006697.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006698.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006699.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006701.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006702.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006703.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006706.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006707.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006709.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006711.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006713.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006714.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006717.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006718.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006719.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006721.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006722.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006723.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006726.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006727.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006729.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006731.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006733.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006734.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006737.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006738.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006739.png does not exist, skipping.
Frame path graph_dataset/raw_scans/iphone/3578aa5730/rgb_frames/006741.png does not exist, skipping.

In [8]:
images_db = np.array(images_db)
images_db.shape

(9816, 960, 720, 3)

In [10]:
im_db_set = {
    "images": images_db,
    "images_captions": detected_objects,
    "i_label": labels,
    "label2i": labels2idx
}

with open("./image_db.pkl", 'wb') as f:
    pickle.dump(im_db_set, f)

In [2]:
data = load_spot_data(window_size=5)

100%|██████████| 214/214 [00:09<00:00, 22.37it/s]

[[      1.841       1.841       1.841 ...      22.585      22.544      22.417]
 [     1.8407      1.8407      1.8407 ...      22.585      22.544      22.418]
 [     1.8412      1.8412      1.8412 ...      22.585      22.544      22.417]
 ...
 [     28.579      28.579      28.579 ...      5.1672      5.2041       5.321]
 [      27.24       27.24       27.24 ...      4.0136      4.0452       4.148]
 [     26.024      26.024      26.024 ...      3.1389      3.1609      3.2373]]

In [3]:
len(data["db_images"])

10171

In [4]:
len(data["ts"])

1278

In [4]:
data['ground_truth'][10][1][-1]

8419

In [3]:
import pickle

with open("spot_dataset_w_gt_5m.pkl", "wb") as f:
    pickle.dump(data, f)

In [13]:
np.array(data["ts"]) == 0

array([ True,  True,  True, ..., False, False, False])